//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class datphong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public datphong()
        {
            this.hoadons = new HashSet<hoadon>();
            this.phongs = new HashSet<phong>();
        }
    
        public string madp { get; set; }
        public string manv { get; set; }
        public string makh { get; set; }
        public string tenlp { get; set; }
        public System.DateTime ngaydat { get; set; }
        public System.DateTime ngayden { get; set; }
        public System.DateTime ngaydi { get; set; }
        public Nullable<int> tiendatcoc { get; set; }
        public int soluong { get; set; }
        public Nullable<bool> trangthai { get; set; }
    
        public virtual khachhang khachhang { get; set; }
        public virtual nhanvien nhanvien { get; set; }
        public virtual loaiphong loaiphong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoadon> hoadons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<phong> phongs { get; set; }
    }
}
