//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadon
    {
        public string mahd { get; set; }
        public string madp { get; set; }
        public System.DateTime ngaylap { get; set; }
        public int tongtien { get; set; }
    
        public virtual datphong datphong { get; set; }
    }
}
