//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLKSCEntities : DbContext
    {
        public QLKSCEntities()
            : base("name=QLKSCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chucvu> chucvus { get; set; }
        public virtual DbSet<datphong> datphongs { get; set; }
        public virtual DbSet<hoadon> hoadons { get; set; }
        public virtual DbSet<khachhang> khachhangs { get; set; }
        public virtual DbSet<loaiphong> loaiphongs { get; set; }
        public virtual DbSet<nhanvien> nhanviens { get; set; }
        public virtual DbSet<phanquyen> phanquyens { get; set; }
        public virtual DbSet<phong> phongs { get; set; }
        public virtual DbSet<quyennv> quyennvs { get; set; }
    
        public virtual ObjectResult<getdskh_Result> getdskh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getdskh_Result>("getdskh");
        }
    
        public virtual ObjectResult<getdsnv_Result> getdsnv()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getdsnv_Result>("getdsnv");
        }
    
        public virtual ObjectResult<gethoadon_Result> gethoadon(string madp)
        {
            var madpParameter = madp != null ?
                new ObjectParameter("madp", madp) :
                new ObjectParameter("madp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gethoadon_Result>("gethoadon", madpParameter);
        }
    }
}
