//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhanvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nhanvien()
        {
            this.datphongs = new HashSet<datphong>();
            this.quyennvs = new HashSet<quyennv>();
        }
    
        public string manv { get; set; }
        public string macv { get; set; }
        public string hoten { get; set; }
        public System.DateTime ngaysinh { get; set; }
        public string gioitinh { get; set; }
        public string sdt { get; set; }
        public string cmnd { get; set; }
        public string diachi { get; set; }
        public string email { get; set; }
    
        public virtual chucvu chucvu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<datphong> datphongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quyennv> quyennvs { get; set; }
    }
}
